//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 30/12/2012 16:19:02
namespace LogbookApp.Data.LocalOData.ServiceReference
{
    
    /// <summary>
    /// There are no comments for PilotsLogBookContainer in the schema.
    /// </summary>
    public partial class PilotsLogBookContainer : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PilotsLogBookContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PilotsLogBookContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("PilotsLogBook", global::System.StringComparison.Ordinal))
            {
                return global::System.Reflection.IntrospectionExtensions.GetTypeInfo(this.GetType()).Assembly.GetType(string.Concat("LogbookApp.Data.LocalOData.ServiceReference", typeName.Substring(13)));
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("LogbookApp.Data.LocalOData.ServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("PilotsLogBook.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for AcTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<AcType> AcTypes
        {
            get
            {
                if ((this._AcTypes == null))
                {
                    this._AcTypes = base.CreateQuery<AcType>("AcTypes");
                }
                return this._AcTypes;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<AcType> _AcTypes;
        /// <summary>
        /// There are no comments for Airfields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Airfield> Airfields
        {
            get
            {
                if ((this._Airfields == null))
                {
                    this._Airfields = base.CreateQuery<Airfield>("Airfields");
                }
                return this._Airfields;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Airfield> _Airfields;
        /// <summary>
        /// There are no comments for Capacities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Capacity> Capacities
        {
            get
            {
                if ((this._Capacities == null))
                {
                    this._Capacities = base.CreateQuery<Capacity>("Capacities");
                }
                return this._Capacities;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Capacity> _Capacities;
        /// <summary>
        /// There are no comments for Flights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Flight> Flights
        {
            get
            {
                if ((this._Flights == null))
                {
                    this._Flights = base.CreateQuery<Flight>("Flights");
                }
                return this._Flights;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Flight> _Flights;
        /// <summary>
        /// There are no comments for AcTypes in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAcTypes(AcType acType)
        {
            base.AddObject("AcTypes", acType);
        }
        /// <summary>
        /// There are no comments for Airfields in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAirfields(Airfield airfield)
        {
            base.AddObject("Airfields", airfield);
        }
        /// <summary>
        /// There are no comments for Capacities in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCapacities(Capacity capacity)
        {
            base.AddObject("Capacities", capacity);
        }
        /// <summary>
        /// There are no comments for Flights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFlights(Flight flight)
        {
            base.AddObject("Flights", flight);
        }
    }
    /// <summary>
    /// There are no comments for PilotsLogBook.AcType in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("AcTypes")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class AcType : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new AcType object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static AcType CreateAcType(long ID)
        {
            AcType acType = new AcType();
            acType.id = ID;
            return acType;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Flights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Flight> Flights
        {
            get
            {
                return this._Flights;
            }
            set
            {
                this._Flights = value;
                this.OnPropertyChanged("Flights");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Flight> _Flights = new global::System.Data.Services.Client.DataServiceCollection<Flight>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PilotsLogBook.Airfield in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Airfields")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Airfield : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Airfield object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Airfield CreateAirfield(long ID)
        {
            Airfield airfield = new Airfield();
            airfield.id = ID;
            return airfield;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property ICAOCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ICAOCode
        {
            get
            {
                return this._ICAOCode;
            }
            set
            {
                this.OnICAOCodeChanging(value);
                this._ICAOCode = value;
                this.OnICAOCodeChanged();
                this.OnPropertyChanged("ICAOCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ICAOCode;
        partial void OnICAOCodeChanging(string value);
        partial void OnICAOCodeChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Flights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Flight> Flights
        {
            get
            {
                return this._Flights;
            }
            set
            {
                this._Flights = value;
                this.OnPropertyChanged("Flights");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Flight> _Flights = new global::System.Data.Services.Client.DataServiceCollection<Flight>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for Flights1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Flight> Flights1
        {
            get
            {
                return this._Flights1;
            }
            set
            {
                this._Flights1 = value;
                this.OnPropertyChanged("Flights1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Flight> _Flights1 = new global::System.Data.Services.Client.DataServiceCollection<Flight>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PilotsLogBook.Capacity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Capacities")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class Capacity : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Capacity object.
        /// </summary>
        /// <param name="ID">Initial value of id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Capacity CreateCapacity(long ID)
        {
            Capacity capacity = new Capacity();
            capacity.id = ID;
            return capacity;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _id;
        partial void OnidChanging(long value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property Code in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                this.OnCodeChanging(value);
                this._Code = value;
                this.OnCodeChanged();
                this.OnPropertyChanged("Code");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Code;
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        /// <summary>
        /// There are no comments for Flights in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Flight> Flights
        {
            get
            {
                return this._Flights;
            }
            set
            {
                this._Flights = value;
                this.OnPropertyChanged("Flights");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Flight> _Flights = new global::System.Data.Services.Client.DataServiceCollection<Flight>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PilotsLogBook.Flight in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Flights")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Flight : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Flight object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Flight CreateFlight(long ID)
        {
            Flight flight = new Flight();
            flight.Id = ID;
            return flight;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public long Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private long _Id;
        partial void OnIdChanging(long value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Reg in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Reg
        {
            get
            {
                return this._Reg;
            }
            set
            {
                this.OnRegChanging(value);
                this._Reg = value;
                this.OnRegChanged();
                this.OnPropertyChanged("Reg");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Reg;
        partial void OnRegChanging(string value);
        partial void OnRegChanged();
        /// <summary>
        /// There are no comments for Property Depart in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Depart
        {
            get
            {
                return this._Depart;
            }
            set
            {
                this.OnDepartChanging(value);
                this._Depart = value;
                this.OnDepartChanged();
                this.OnPropertyChanged("Depart");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Depart;
        partial void OnDepartChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDepartChanged();
        /// <summary>
        /// There are no comments for Property Captain in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Captain
        {
            get
            {
                return this._Captain;
            }
            set
            {
                this.OnCaptainChanging(value);
                this._Captain = value;
                this.OnCaptainChanged();
                this.OnPropertyChanged("Captain");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Captain;
        partial void OnCaptainChanging(string value);
        partial void OnCaptainChanged();
        /// <summary>
        /// There are no comments for Property Arrival in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Arrival
        {
            get
            {
                return this._Arrival;
            }
            set
            {
                this.OnArrivalChanging(value);
                this._Arrival = value;
                this.OnArrivalChanged();
                this.OnPropertyChanged("Arrival");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Arrival;
        partial void OnArrivalChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnArrivalChanged();
        /// <summary>
        /// There are no comments for Property Date in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTimeOffset> Date
        {
            get
            {
                return this._Date;
            }
            set
            {
                this.OnDateChanging(value);
                this._Date = value;
                this.OnDateChanged();
                this.OnPropertyChanged("Date");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _Date;
        partial void OnDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateChanged();
        /// <summary>
        /// There are no comments for Property AcTypeId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> AcTypeId
        {
            get
            {
                return this._AcTypeId;
            }
            set
            {
                this.OnAcTypeIdChanging(value);
                this._AcTypeId = value;
                this.OnAcTypeIdChanged();
                this.OnPropertyChanged("AcTypeId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _AcTypeId;
        partial void OnAcTypeIdChanging(global::System.Nullable<long> value);
        partial void OnAcTypeIdChanged();
        /// <summary>
        /// There are no comments for Property FromAirfieldId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> FromAirfieldId
        {
            get
            {
                return this._FromAirfieldId;
            }
            set
            {
                this.OnFromAirfieldIdChanging(value);
                this._FromAirfieldId = value;
                this.OnFromAirfieldIdChanged();
                this.OnPropertyChanged("FromAirfieldId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _FromAirfieldId;
        partial void OnFromAirfieldIdChanging(global::System.Nullable<long> value);
        partial void OnFromAirfieldIdChanged();
        /// <summary>
        /// There are no comments for Property CapacityId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> CapacityId
        {
            get
            {
                return this._CapacityId;
            }
            set
            {
                this.OnCapacityIdChanging(value);
                this._CapacityId = value;
                this.OnCapacityIdChanged();
                this.OnPropertyChanged("CapacityId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _CapacityId;
        partial void OnCapacityIdChanging(global::System.Nullable<long> value);
        partial void OnCapacityIdChanged();
        /// <summary>
        /// There are no comments for Property ToAirfieldId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> ToAirfieldId
        {
            get
            {
                return this._ToAirfieldId;
            }
            set
            {
                this.OnToAirfieldIdChanging(value);
                this._ToAirfieldId = value;
                this.OnToAirfieldIdChanged();
                this.OnPropertyChanged("ToAirfieldId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _ToAirfieldId;
        partial void OnToAirfieldIdChanging(global::System.Nullable<long> value);
        partial void OnToAirfieldIdChanged();
        /// <summary>
        /// There are no comments for AcType in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public AcType AcType
        {
            get
            {
                return this._AcType;
            }
            set
            {
                this._AcType = value;
                this.OnPropertyChanged("AcType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private AcType _AcType;
        /// <summary>
        /// There are no comments for Airfield in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Airfield Airfield
        {
            get
            {
                return this._Airfield;
            }
            set
            {
                this._Airfield = value;
                this.OnPropertyChanged("Airfield");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Airfield _Airfield;
        /// <summary>
        /// There are no comments for Airfield1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Airfield Airfield1
        {
            get
            {
                return this._Airfield1;
            }
            set
            {
                this._Airfield1 = value;
                this.OnPropertyChanged("Airfield1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Airfield _Airfield1;
        /// <summary>
        /// There are no comments for Capacity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Capacity Capacity
        {
            get
            {
                return this._Capacity;
            }
            set
            {
                this._Capacity = value;
                this.OnPropertyChanged("Capacity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Capacity _Capacity;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
